### ISSUE TITLE
How low of the validation loss you can get on LJ dataset?

### ISSUE THREAD

**Issue by wenyong-h** [NVIDIA/tacotron2#69] opened 2018-08-08 13:42 UTC
I'm following the README to train on LJ dataset.
My validation loss is about 4.67 after 5 days of training on a single P100 GPU. Now the validation loss decreases very slow.
The generated audio sample with Griffin-Lim have significant background noise, even when in the middle of a pause, though the pronunciation and prosody seem good enough.

**Comment by gsoul** [comment] 2018-08-08 15:11
0.44 on 2*1080ti in fp16 after ~36k steps

**Comment by wenyong-h** [comment] 2018-08-09 13:37
I remember wrong, my  validation loss is about 0.467 with fp16.
So the  validation loss seems to have no problem, feel free to close this issue.
BTW, Does your generated audio sample with Griffin-Lim also have background noise?

**Comment by gsoul** [comment] 2018-08-09 15:09
yes it does.

And I have no permissions to close the issue, so please do so if the issue is resolved.

**Comment by jferrer21** [comment] 2018-08-09 18:41
@wenyong-h 
How long it took to train with fp16  the Griffin-Lim and or LJ dataset? 

@gsoul
 Which GPU are you using?

**Comment by wenyong-h** [comment] 2018-08-10 16:02
Training with fp16 takes about 3 days  on my machine with a single P100.
The dataset is LJ dataset.

**Comment by rafaelvalle** [comment] 2018-11-27 16:25
Closing due to inactivity.

**Closed by rafaelvalle** 2018-11-27 16:25 UTC
