### ISSUE TITLE
Impossible to change n_frames_per_step

### ISSUE THREAD

**Issue by yliess86** [NVIDIA/tacotron2#29] opened 2018-06-07 08:35 UTC
First of all I would like to thank you for this incredible and clean repository. 

I am actualy working on a school project and I need to perform TTS. The problem is that I only have a 8Go GPU (NVIDIA GeForce GTX 980M) and I can't afford a cloud instance or some sort of a AI Machine. So in order to make the training work I had to bring down the batch size to 24. I also tried, after reading the paper and the Rayhan's implementation, to set the n_frames_per_step to 5 and encountered some issues.

Here are some of the issues I have:

**1.  n_frames_per_step can't be changed:**
If i try to set n_frames_per_step to any value other than 1 (here 5) I get this error.

```
Epoch: 0
Traceback (most recent call last):
  File "train.py", line 288, in <module>
    args.warm_start, args.n_gpus, args.rank, args.group_name, hparams)
  File "train.py", line 213, in train
    y_pred = model(x)
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/module.py", line 491, in __call__
    result = self.forward(*input, **kwargs)
  File "/media/yliess/Storage/Projects/tacotron2-master/model.py", line 508, in forward
    encoder_outputs, targets, memory_lengths=input_lengths)
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/module.py", line 491, in __call__
    result = self.forward(*input, **kwargs)
  File "/media/yliess/Storage/Projects/tacotron2-master/model.py", line 395, in forward
    decoder_inputs = self.parse_decoder_inputs(decoder_inputs)
  File "/media/yliess/Storage/Projects/tacotron2-master/model.py", line 307, in parse_decoder_inputs
    int(decoder_inputs.size(1)/self.n_frames_per_step), -1)
RuntimeError: invalid argument 2: View size is not compatible with input tensor's size and stride (at least one dimension spans across two contiguous subspaces). Call .contiguous() before .view(). at /pytorch/aten/src/THC/generic/THCTensor.c:276
```

**2. I have trained on the LJ Speech dataset  for about 4 days and the loss is stucked between 0.7 and 0.5 after some iterations and does not go further**:

I am actually at the 27500 iterations and the loss is stucked. I also don't see any improvement on the attention alignement. How long do you think it will take ?

```
Train loss 28001 0.573519 Grad Norm 1.283919 5.50s/it
Train loss 28002 0.616863 Grad Norm 2.458358 5.09s/it
Train loss 28003 0.562185 Grad Norm 1.225074 5.42s/it
Train loss 28004 0.551899 Grad Norm 1.262375 5.45s/it
Train loss 28005 0.545977 Grad Norm 0.926398 5.34s/it
Train loss 28006 0.611665 Grad Norm 0.943002 5.68s/it
Train loss 28007 0.599455 Grad Norm 0.933666 5.64s/it
Train loss 28008 0.632478 Grad Norm 0.780330 5.38s/it
Train loss 28009 0.648359 Grad Norm 0.839933 5.14s/it
Train loss 28010 0.605244 Grad Norm 1.070807 5.34s/it
Train loss 28011 0.582034 Grad Norm 0.945326 5.23s/it
```
This is the training loss from the 8k step to the 28k:
![loss](https://image.ibb.co/nsJBNo/loss.png)

**Comment by rafaelvalle** [comment] 2018-06-07 14:33
For 1, give us some time to debug the code.
For 2, can you please file a separate issue  and include your curves and alignment plots?

**Comment by yliess86** [comment] 2018-06-07 16:14
Thank you for this response.
1. I'll wait for it thank you.
2. Here is the new [issue](https://github.com/NVIDIA/tacotron2/issues/30)

**Comment by rafaelvalle** [comment] 2018-06-07 20:04
We currently only support 1 frame per step. 
Please submit a PR if you modify the code to support multiple frames per step: it requires modifying the gating mechanism.

**Comment by rafaelvalle** [comment] 2018-06-08 15:20
Closing. Please re-open if you think the issue is not solved.

**Closed by rafaelvalle** 2018-06-08 15:20 UTC
